import { useEffect, useMemo, useState } from "react";
import {
  Activity,
  AlertTriangle,
  ArrowDownRight,
  ArrowUpRight,
  BarChart3,
  Check,
  ChevronRight,
  CircleDot,
  Clock3,
  Command,
  Cpu,
  Crosshair,
  Globe2,
  LockKeyhole,
  Menu,
  Radio,
  RotateCcw,
  Satellite,
  Shield,
  ShieldAlert,
  Signal,
  Sparkles,
  Terminal,
  Wifi,
  X,
} from "lucide-react";
import SatelliteCybersecurityMap from "./components/SatelliteCybersecurityMap";

type Language = "en" | "ar";
type ScenarioId = "command" | "pattern" | "login";
type Severity = "info" | "warning" | "critical";

type ActivityItem = {
  time: string;
  title: string;
  detail: string;
  severity: Severity;
  code: string;
};

const HERO_URL = "/hero-space.webp";

const copy = {
  en: {
    nav: { overview: "Overview", dashboard: "Live dashboard", simulator: "Threat simulator", brief: "Project brief" },
    eyebrow: "WORLD SPACE WEEK 2026 · UHB INNOVATION PROJECT",
    titleA: "Protect the signal.",
    titleB: "Explain the threat.",
    heroBody: "SpaceShield is an educational cybersecurity prototype that makes satellite communication risks visible through synthetic telemetry, safe simulations, and clear response logic.",
    openDashboard: "Open live dashboard",
    exploreProject: "Explore the project",
    prototypeBadge: "Educational prototype",
    synthetic: "100% synthetic data",
    noConnection: "No real systems connected",
    mission: "MISSION CONTROL / EDUCATION MODE",
    online: "All simulated links nominal",
    snapshot: "SYSTEM SNAPSHOT",
    health: "System health",
    nominal: "Nominal",
    live: "Live simulation",
    monitored: "Monitored assets",
    alerts: "Open alerts",
    risk: "Threat level",
    low: "Low",
    dashboardTitle: "Satellite cybersecurity dashboard",
    dashboardIntro: "A calm, live-looking view of synthetic orbital telemetry and security events.",
    lastSync: "Last synthetic sync",
    secAgo: "seconds ago",
    connections: "Simulated connections",
    secure: "SECURE",
    activity: "Communication activity",
    activitySub: "Synthetic packets / 24h window",
    packets: "packets",
    linkQuality: "Link quality",
    uplink: "Uplink",
    downlink: "Downlink",
    log: "Activity log",
    logSub: "Events generated by the simulator",
    noEvents: "No active incidents. The synthetic perimeter is quiet.",
    simulatorEyebrow: "SAFE SCENARIO LAB",
    simulatorTitle: "Test the response layer",
    simulatorBody: "Trigger a synthetic event to see how SpaceShield classifies, contains, and explains the signal. Nothing leaves this browser.",
    run: "Run scenario",
    reset: "Reset simulation",
    response: "SPACE SHIELD RESPONSE",
    detected: "Scenario detected",
    contained: "Contained in simulation",
    scenarioCommand: "Unauthorized command attempt",
    scenarioCommandDesc: "A command signature appears outside the expected ground-station window.",
    scenarioPattern: "Suspicious communication pattern",
    scenarioPatternDesc: "Packet timing and volume drift from the synthetic mission baseline.",
    scenarioLogin: "Unknown ground-station login",
    scenarioLoginDesc: "A login attempt arrives from an unregistered synthetic station ID.",
    commandResponse: "Command rejected, session isolated, and the event added to the audit trail.",
    patternResponse: "Pattern flagged for analyst review; synthetic traffic is rate-limited while context is gathered.",
    loginResponse: "Access denied, token revoked, and the synthetic station is placed in observation mode.",
    why: "Why space cybersecurity matters",
    whyBody: "Satellites support communication, navigation, climate observation, and emergency response. Protecting the command-and-control layer is part of protecting the services people depend on below.",
    problem: "The problem",
    problemBody: "Space systems are remote, complex, and increasingly connected. A small anomaly can be difficult to contextualize when operators have limited visibility across the full signal path.",
    solution: "The proposed solution",
    solutionBody: "SpaceShield presents an explainable monitoring layer that combines synthetic telemetry, event classification, and response guidance in one learning environment.",
    method: "Methodology",
    methodBody: "Model the signal → inject safe synthetic scenarios → classify the event → show the response → record the learning outcome.",
    impact: "Expected impact",
    impactBody: "Help students and evaluators understand how cybersecurity thinking applies to space technology without touching real infrastructure.",
    briefEyebrow: "ACADEMIC PROJECT BRIEF",
    briefTitle: "A prototype made for evaluation",
    abstract: "Abstract",
    abstractBody: "SpaceShield is an educational prototype for visualizing satellite cybersecurity monitoring. It simulates communication telemetry and three safe incident scenarios so learners can connect a suspicious signal to a documented response.",
    objectives: "Objectives",
    objectiveItems: ["Translate space-cyber concepts into an interactive interface.", "Demonstrate safe incident classification and response logic.", "Create a clear academic artifact for discussion and evaluation."],
    prototypeDemo: "Prototype demonstration",
    demoBody: "Use the threat simulator above to demonstrate the response loop during your presentation. Each event is deterministic, reversible, and synthetic.",
    studentDetails: "Student details",
    fullName: "Full name",
    college: "College / department",
    academic: "Academic details",
    placeholderName: "[Your full name]",
    placeholderCollege: "[College / Cybersecurity department]",
    placeholderAcademic: "[Course · supervisor · section]",
    disclaimer: "Important boundary",
    disclaimerBody: "SpaceShield is an educational prototype. It uses synthetic data only, does not connect to satellites or ground stations, and must not be used to test real systems.",
    footer: "Built as a student innovation project for World Space Week 2026 · University of Hafr Al Batin",
    ready: "Ready for demonstration",
    language: "العربية",
    signalStable: "Signal stable",
    eventAdded: "Synthetic event added to activity log.",
    mapEyebrow: "SATELLITE CYBERSECURITY MAP",
    mapTitle: "Orbital signal map",
    mapIntro: "Synthetic satellites, ground stations, and animated communication paths in one control-center view.",
    interactive: "Interactive",
    panHint: "Drag to pan · scroll to zoom · click a node for details",
    legend: "Legend",
    safe: "Secure",
    review: "Review",
    threat: "Threat",
    satellites: "Satellites",
    groundStations: "Ground stations",
    clickDetails: "Click a node for details",
    threatBanner: "THREAT PATH DETECTED",
    clearThreat: "Clear threat",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    resetView: "Reset map view",
    connection: "Connection",
    lastActivity: "Last activity",
    status: "Status",
    close: "Close details",
  },
  ar: {
    nav: { overview: "نظرة عامة", dashboard: "لوحة المراقبة", simulator: "محاكي التهديدات", brief: "ملخص المشروع" },
    eyebrow: "أسبوع الفضاء العالمي 2026 · مشروع ابتكار طلابي بجامعة حفر الباطن",
    titleA: "احمِ الإشارة.",
    titleB: "واشرح التهديد.",
    heroBody: "SpaceShield نموذج تعليمي للأمن السيبراني يجعل مخاطر اتصالات الأقمار الصناعية واضحة من خلال بيانات اصطناعية ومحاكاة آمنة ومنطق استجابة مفهوم.",
    openDashboard: "افتح لوحة المراقبة",
    exploreProject: "استكشف المشروع",
    prototypeBadge: "نموذج تعليمي",
    synthetic: "بيانات اصطناعية بالكامل",
    noConnection: "لا يوجد اتصال بأنظمة حقيقية",
    mission: "مركز التحكم / الوضع التعليمي",
    online: "جميع الروابط المحاكاة مستقرة",
    snapshot: "ملخص النظام",
    health: "سلامة النظام",
    nominal: "طبيعي",
    live: "محاكاة مباشرة",
    monitored: "الأصول المراقبة",
    alerts: "التنبيهات المفتوحة",
    risk: "مستوى التهديد",
    low: "منخفض",
    dashboardTitle: "لوحة الأمن السيبراني للقمر الصناعي",
    dashboardIntro: "عرض حي المظهر لبيانات المدار الاصطناعية وأحداث الأمن المحاكاة.",
    lastSync: "آخر مزامنة اصطناعية",
    secAgo: "ثوانٍ مضت",
    connections: "الاتصالات المحاكاة",
    secure: "آمن",
    activity: "نشاط الاتصالات",
    activitySub: "حزم اصطناعية / نافذة 24 ساعة",
    packets: "حزمة",
    linkQuality: "جودة الرابط",
    uplink: "الرفع",
    downlink: "التنزيل",
    log: "سجل النشاط",
    logSub: "الأحداث التي أنشأها المحاكي",
    noEvents: "لا توجد حوادث نشطة. المحيط الاصطناعي هادئ.",
    simulatorEyebrow: "مختبر السيناريوهات الآمنة",
    simulatorTitle: "اختبر طبقة الاستجابة",
    simulatorBody: "فعّل حدثاً اصطناعياً لترى كيف يصنّف SpaceShield الإشارة ويحتويها ويشرحها. لا يغادر أي شيء هذا المتصفح.",
    run: "تشغيل السيناريو",
    reset: "إعادة ضبط المحاكاة",
    response: "استجابة SPACESHIELD",
    detected: "تم اكتشاف السيناريو",
    contained: "تم الاحتواء داخل المحاكاة",
    scenarioCommand: "محاولة أمر غير مصرح",
    scenarioCommandDesc: "ظهرت بصمة أمر خارج نافذة المحطة الأرضية المتوقعة.",
    scenarioPattern: "نمط اتصالات مشبوه",
    scenarioPatternDesc: "يختلف توقيت الحزم وحجمها عن خط المهمة الاصطناعي.",
    scenarioLogin: "دخول من محطة أرضية مجهولة",
    scenarioLoginDesc: "وصلت محاولة دخول من معرّف محطة اصطناعية غير مسجل.",
    commandResponse: "تم رفض الأمر وعزل الجلسة وإضافة الحدث إلى سجل التدقيق.",
    patternResponse: "تم تصنيف النمط لمراجعة المحلل؛ تم تحديد معدل الحركة الاصطناعية أثناء جمع السياق.",
    loginResponse: "تم رفض الوصول وإلغاء الرمز ووضع المحطة الاصطناعية في وضع المراقبة.",
    why: "لماذا يهم الأمن السيبراني الفضائي",
    whyBody: "تدعم الأقمار الصناعية الاتصالات والملاحة ومراقبة المناخ والاستجابة للطوارئ. حماية طبقة القيادة والتحكم جزء من حماية الخدمات التي يعتمد عليها الناس على الأرض.",
    problem: "المشكلة",
    problemBody: "الأنظمة الفضائية بعيدة ومعقدة ومتصلة بشكل متزايد. قد يكون من الصعب فهم شذوذ صغير عند محدودية رؤية المشغل لمسار الإشارة الكامل.",
    solution: "الحل المقترح",
    solutionBody: "يعرض SpaceShield طبقة مراقبة قابلة للتفسير تجمع البيانات الاصطناعية وتصنيف الأحداث وإرشادات الاستجابة في بيئة تعليمية واحدة.",
    method: "المنهجية",
    methodBody: "نمذجة الإشارة ← حقن سيناريوهات اصطناعية آمنة ← تصنيف الحدث ← عرض الاستجابة ← تسجيل نتيجة التعلم.",
    impact: "الأثر المتوقع",
    impactBody: "مساعدة الطلاب والمقيّمين على فهم تطبيق التفكير السيبراني على تقنية الفضاء دون لمس بنية تحتية حقيقية.",
    briefEyebrow: "ملخص المشروع الأكاديمي",
    briefTitle: "نموذج أولي جاهز للتقييم",
    abstract: "الملخص",
    abstractBody: "SpaceShield نموذج تعليمي لتصور مراقبة الأمن السيبراني للأقمار الصناعية. يحاكي بيانات الاتصالات وثلاثة سيناريوهات حوادث آمنة لمساعدة المتعلم على ربط الإشارة المشبوهة بالاستجابة الموثقة.",
    objectives: "الأهداف",
    objectiveItems: ["تحويل مفاهيم الأمن السيبراني الفضائي إلى واجهة تفاعلية.", "عرض منطق آمن لتصنيف الحوادث والاستجابة لها.", "إنشاء مادة أكاديمية واضحة للنقاش والتقييم."],
    prototypeDemo: "عرض النموذج الأولي",
    demoBody: "استخدم محاكي التهديدات أعلاه لعرض حلقة الاستجابة أثناء تقديمك. كل حدث حتمي وقابل للعكس واصطناعي.",
    studentDetails: "بيانات الطالب",
    fullName: "الاسم الكامل",
    college: "الكلية / القسم",
    academic: "التفاصيل الأكاديمية",
    placeholderName: "[اكتب اسمك الكامل]",
    placeholderCollege: "[الكلية / قسم الأمن السيبراني]",
    placeholderAcademic: "[المقرر · المشرف · الشعبة]",
    disclaimer: "حدود مهمة",
    disclaimerBody: "SpaceShield نموذج تعليمي. يستخدم بيانات اصطناعية فقط، ولا يتصل بالأقمار الصناعية أو المحطات الأرضية، ولا يجوز استخدامه لاختبار الأنظمة الحقيقية.",
    footer: "مشروع ابتكار طلابي لأسبوع الفضاء العالمي 2026 · جامعة حفر الباطن",
    ready: "جاهز للعرض",
    language: "English",
    signalStable: "الإشارة مستقرة",
    eventAdded: "تمت إضافة حدث اصطناعي إلى سجل النشاط.",
    mapEyebrow: "خريطة الأمن السيبراني الفضائي",
    mapTitle: "خريطة الإشارات المدارية",
    mapIntro: "أقمار صناعية ومحطات أرضية ومسارات اتصالات متحركة اصطناعية في عرض تحكم واحد.",
    interactive: "تفاعلية",
    panHint: "اسحب للتحريك · مرر للتكبير · اضغط على عقدة للتفاصيل",
    legend: "دليل الألوان",
    safe: "آمن",
    review: "يحتاج فحصاً",
    threat: "تهديد",
    satellites: "الأقمار الصناعية",
    groundStations: "المحطات الأرضية",
    clickDetails: "اضغط على عقدة للتفاصيل",
    threatBanner: "تم اكتشاف مسار تهديد",
    clearThreat: "مسح التهديد",
    zoomIn: "تكبير",
    zoomOut: "تصغير",
    resetView: "إعادة ضبط الخريطة",
    connection: "نوع الاتصال",
    lastActivity: "آخر نشاط",
    status: "الحالة",
    close: "إغلاق التفاصيل",
  },
} as const;

const scenarios: { id: ScenarioId; icon: typeof Command; key: "command" | "pattern" | "login"; severity: Severity }[] = [
  { id: "command", icon: Command, key: "command", severity: "critical" },
  { id: "pattern", icon: Activity, key: "pattern", severity: "warning" },
  { id: "login", icon: LockKeyhole, key: "login", severity: "warning" },
];

const baseActivity: ActivityItem[] = [
  { time: "14:32:08", title: "Telemetry heartbeat received", detail: "SAT-07 · relay window nominal", severity: "info", code: "TEL-200" },
  { time: "14:31:42", title: "Ground station handshake verified", detail: "GS-RIY-02 · token matched", severity: "info", code: "AUTH-104" },
  { time: "14:30:17", title: "Uplink packet batch normalized", detail: "1,248 packets · 99.8% integrity", severity: "info", code: "NET-118" },
  { time: "14:28:54", title: "Orbital pass context updated", detail: "LEO corridor · synthetic schedule", severity: "info", code: "ORB-032" },
];

const scenarioText = {
  command: { title: "Unauthorized command attempt", detail: "CMD-774 · signature outside expected window", response: "Command rejected, session isolated, and the event added to the audit trail.", responseAr: "تم رفض الأمر وعزل الجلسة وإضافة الحدث إلى سجل التدقيق." },
  pattern: { title: "Suspicious communication pattern", detail: "NET-441 · synthetic volume drift detected", response: "Pattern flagged for analyst review; synthetic traffic is rate-limited while context is gathered.", responseAr: "تم تصنيف النمط لمراجعة المحلل؛ تم تحديد معدل الحركة الاصطناعية أثناء جمع السياق." },
  login: { title: "Unknown ground-station login", detail: "AUTH-529 · station ID not in allowlist", response: "Access denied, token revoked, and the synthetic station is placed in observation mode.", responseAr: "تم رفض الوصول وإلغاء الرمز ووضع المحطة الاصطناعية في وضع المراقبة." },
};

function nowTime() {
  return new Intl.DateTimeFormat("en-GB", { hour: "2-digit", minute: "2-digit", second: "2-digit", hour12: false }).format(new Date());
}

function scrollToId(id: string) {
  document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" });
}

function Logo({ compact = false }: { compact?: boolean }) {
  return (
    <span className={`brand ${compact ? "brand-compact" : ""}`}>
      <span className="brand-mark"><Shield size={20} strokeWidth={2.2} /><span className="brand-orbit" /></span>
      {!compact && <span className="brand-word">Space<span>Shield</span></span>}
    </span>
  );
}

function StatusPill({ children, tone = "mint" }: { children: React.ReactNode; tone?: "mint" | "blue" | "amber" | "coral" }) {
  return <span className={`status-pill ${tone}`}><span className="status-dot" />{children}</span>;
}

function Sparkline({ values, color = "cyan" }: { values: number[]; color?: "cyan" | "mint" | "amber" }) {
  const max = Math.max(...values);
  const min = Math.min(...values);
  const points = values.map((value, index) => {
    const x = (index / (values.length - 1)) * 100;
    const y = 34 - ((value - min) / Math.max(max - min, 1)) * 26;
    return `${x},${y}`;
  }).join(" ");
  return <svg className={`sparkline ${color}`} viewBox="0 0 100 40" preserveAspectRatio="none" role="img" aria-label="Synthetic activity chart"><polyline points={points} fill="none" stroke="currentColor" strokeWidth="2" vectorEffect="non-scaling-stroke" /></svg>;
}

function App() {
  const [language, setLanguage] = useState<Language>("en");
  const [activeScenario, setActiveScenario] = useState<ScenarioId | null>(null);
  const [activity, setActivity] = useState<ActivityItem[]>(baseActivity);
  const [mobileOpen, setMobileOpen] = useState(false);
  const t = copy[language];
  const isArabic = language === "ar";
  const alertCount = activeScenario ? 1 : 0;
  const activeScenarioDetails = activeScenario ? scenarioText[activeScenario] : null;
  const statusLabel = activeScenario ? (isArabic ? "يحتاج مراجعة" : "Review needed") : t.nominal;

  useEffect(() => {
    document.documentElement.lang = language;
    document.documentElement.dir = isArabic ? "rtl" : "ltr";
  }, [isArabic, language]);

  const chartBars = useMemo(() => [38, 48, 42, 68, 51, 75, 63, 81, 72, 88, 66, 78, 57, 84, 69, 92], []);
  const navItems = [
    { id: "overview", label: t.nav.overview },
    { id: "dashboard", label: t.nav.dashboard },
    { id: "simulator", label: t.nav.simulator },
    { id: "brief", label: t.nav.brief },
  ];

  const runScenario = (id: ScenarioId) => {
    const data = scenarioText[id];
    const event: ActivityItem = {
      time: nowTime(),
      title: data.title,
      detail: data.detail,
      severity: id === "command" ? "critical" : "warning",
      code: id === "command" ? "CMD-774" : id === "pattern" ? "NET-441" : "AUTH-529",
    };
    setActiveScenario(id);
    setActivity((current) => [event, ...current].slice(0, 6));
  };

  const resetSimulation = () => {
    setActiveScenario(null);
    setActivity(baseActivity);
  };

  return (
    <div className="app-shell" id="top">
      <div className="ambient-grid" aria-hidden="true" />
      <div className="star-field" aria-hidden="true"><i /><i /><i /><i /><i /><i /><i /><i /><i /><i /></div>

      <header className="site-header">
        <div className="container header-inner">
          <button className="logo-button" onClick={() => scrollToId("overview")} aria-label="SpaceShield home"><Logo /></button>
          <nav className={`main-nav ${mobileOpen ? "open" : ""}`} aria-label="Primary navigation">
            {navItems.map((item) => <button key={item.id} onClick={() => { scrollToId(item.id); setMobileOpen(false); }}>{item.label}</button>)}
          </nav>
          <div className="header-actions">
            <button className="language-toggle" onClick={() => setLanguage(language === "en" ? "ar" : "en")} aria-label="Toggle language"><Globe2 size={16} />{t.language}</button>
            <button className="menu-toggle" onClick={() => setMobileOpen((current) => !current)} aria-label="Toggle menu">{mobileOpen ? <X size={20} /> : <Menu size={20} />}</button>
          </div>
        </div>
      </header>

      <main>
        <section className="hero-section section-pad" id="overview">
          <div className="hero-art" style={{ backgroundImage: `url(${HERO_URL})` }} aria-hidden="true" />
          <div className="hero-vignette" aria-hidden="true" />
          <div className="container hero-grid">
            <div className="hero-copy">
              <div className="eyebrow"><span className="eyebrow-line" />{t.eyebrow}</div>
              <h1>{t.titleA}<br /><em>{t.titleB}</em></h1>
              <p className="hero-body">{t.heroBody}</p>
              <div className="hero-cta-row">
                <button className="btn btn-primary" onClick={() => scrollToId("dashboard")}>{t.openDashboard}<ArrowUpRight size={17} /></button>
                <button className="btn btn-ghost" onClick={() => scrollToId("brief")}>{t.exploreProject}<ChevronRight size={16} /></button>
              </div>
              <div className="hero-trust-row">
                <StatusPill tone="mint">{t.prototypeBadge}</StatusPill>
                <span className="micro-note"><Check size={14} />{t.synthetic}</span>
                <span className="micro-note"><LockKeyhole size={13} />{t.noConnection}</span>
              </div>
            </div>
            <div className="orbital-stage" aria-label="Illustration of a simulated satellite in orbit">
              <div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="orbit orbit-three" />
              <div className="earth"><div className="earth-glow" /><div className="earth-surface"><span /><span /><span /></div></div>
              <div className="satellite"><div className="sat-body"><Satellite size={34} /></div><div className="solar-panel left" /><div className="solar-panel right" /><div className="signal-ring" /></div>
              <span className="orbit-label label-a"><span className="label-dot" />SAT-07 / LEO</span>
              <span className="orbit-label label-b">SIMULATED LINK <Signal size={12} /></span>
              <div className="scan-line" />
            </div>
          </div>
          <div className="container hero-bottom-line"><span>{t.mission}</span><span className="scroll-hint"><span className="scroll-wheel" /> Scroll to explore</span><span className="live-indicator"><span />{t.online}</span></div>
        </section>

        <section className="dashboard-section section-pad" id="dashboard">
          <div className="container">
            <div className="section-heading-row">
              <div><div className="eyebrow"><span className="eyebrow-line" />{t.snapshot}</div><h2>{t.dashboardTitle}</h2><p>{t.dashboardIntro}</p></div>
              <div className="sync-readout"><Clock3 size={14} /><span>{t.lastSync}</span><strong>00:08 {t.secAgo}</strong></div>
            </div>
            <div className="metric-grid">
              <article className="panel metric-card metric-health"><div className="metric-top"><span>{t.health}</span><Shield size={16} /></div><strong>{statusLabel}</strong><div className="metric-detail"><StatusPill tone={activeScenario ? "amber" : "mint"}>{activeScenario ? (isArabic ? "تحليل جارٍ" : "Analysis active") : t.live}</StatusPill><span>99.8% {t.signalStable}</span></div><div className="mini-progress"><span style={{ width: activeScenario ? "72%" : "99%" }} /></div></article>
              <article className="panel metric-card"><div className="metric-top"><span>{t.monitored}</span><Satellite size={16} /></div><strong>04 <small>/ 04</small></strong><div className="metric-detail"><span className="metric-up"><ArrowUpRight size={13} /> 12.4%</span><span>{t.connections}</span></div><Sparkline values={[23, 32, 25, 41, 34, 46, 44, 52]} color="cyan" /></article>
              <article className={`panel metric-card ${activeScenario ? "metric-alert" : ""}`}><div className="metric-top"><span>{t.alerts}</span><AlertTriangle size={16} /></div><strong>{String(alertCount).padStart(2, "0")} <small>{activeScenario ? (isArabic ? "نشط" : "active") : (isArabic ? "نشط" : "active")}</small></strong><div className="metric-detail"><span className={activeScenario ? "metric-down" : "metric-up"}>{activeScenario ? <ArrowUpRight size={13} /> : <Check size={13} />} {activeScenario ? "1" : "0"}</span><span>{activeScenario ? (isArabic ? "حدث محاكاة" : "simulated event") : t.noEvents}</span></div><Sparkline values={activeScenario ? [18, 21, 19, 30, 39, 48, 54, 61] : [28, 30, 29, 28, 31, 29, 30, 28]} color={activeScenario ? "amber" : "mint"} /></article>
              <article className="panel metric-card metric-threat"><div className="metric-top"><span>{t.risk}</span><Crosshair size={16} /></div><strong>{activeScenario ? (activeScenario === "command" ? "HIGH" : "MED") : "LOW"}</strong><div className="threat-scale"><span className="filled" /><span className={activeScenario ? "filled" : ""} /><span className={activeScenario === "command" ? "filled critical" : ""} /><span /></div><div className="metric-detail"><span>{activeScenario ? (isArabic ? "استجابة مطلوبة" : "Response required") : t.low}</span><span>AI / ruleset v0.3</span></div></article>
            </div>

            <div className="dashboard-layout">
              <article className="panel chart-panel"><div className="panel-header"><div><span className="panel-kicker"><BarChart3 size={14} />{t.activity}</span><h3>{t.activitySub}</h3></div><div className="chart-legend"><span><i className="legend-dot cyan" />{t.uplink}</span><span><i className="legend-dot mint" />{t.downlink}</span></div></div><div className="chart-area"><div className="chart-y-labels"><span>100</span><span>75</span><span>50</span><span>25</span><span>0</span></div><div className="bars">{chartBars.map((height, index) => <div className="bar-group" key={index}><span className="bar bar-uplink" style={{ height: `${height}%` }} /><span className="bar bar-downlink" style={{ height: `${Math.max(18, height - 17)}%` }} /></div>)}</div><div className="chart-x-labels"><span>00:00</span><span>06:00</span><span>12:00</span><span>18:00</span><span>24:00</span></div></div><div className="chart-footer"><span><span className="live-indicator"><span />{t.live}</span></span><strong>28,416 <small>{t.packets}</small></strong><span className="chart-delta"><ArrowUpRight size={14} /> 8.2% vs baseline</span></div></article>
              <article className="panel link-panel"><div className="panel-header"><div><span className="panel-kicker"><Wifi size={14} />{t.linkQuality}</span><h3>SAT-07 / LEO relay</h3></div><StatusPill tone="mint">{t.secure}</StatusPill></div><div className="link-visual"><div className="link-pulse"><Signal size={32} /></div><div><strong>−42 <small>dBm</small></strong><span>UHF / encrypted simulation</span></div></div><div className="signal-meter">{[1, 1, 1, 1, 1, 1, 0, 0].map((on, i) => <i className={on ? "on" : ""} key={i} />)}</div><div className="link-stats"><div><span>Latency</span><strong>184 ms</strong></div><div><span>Integrity</span><strong>99.8%</strong></div><div><span>Pass window</span><strong>07:42</strong></div></div></article>
            </div>

            <SatelliteCybersecurityMap scenario={activeScenario} copy={t} />

            <article className="panel activity-panel"><div className="panel-header"><div><span className="panel-kicker"><Terminal size={14} />{t.log}</span><h3>{t.logSub}</h3></div><span className="activity-count">{activity.length} / 06</span></div><div className="activity-list">{activity.map((item, index) => <div className={`activity-row ${item.severity}`} key={`${item.code}-${item.time}`}><div className="activity-icon">{item.severity === "critical" ? <ShieldAlert size={16} /> : item.severity === "warning" ? <AlertTriangle size={16} /> : <CircleDot size={16} />}</div><div className="activity-content"><div><strong>{isArabic && index === 0 && activeScenario ? activeScenario === "command" ? t.scenarioCommand : activeScenario === "pattern" ? t.scenarioPattern : t.scenarioLogin : item.title}</strong><span>{item.code}</span></div><p>{isArabic && index === 0 && activeScenario ? activeScenario === "command" ? "بصمة خارج نافذة القيادة المتوقعة" : activeScenario === "pattern" ? "تم اكتشاف انحراف في حجم الحركة الاصطناعية" : "معرّف المحطة غير موجود في القائمة المسموحة" : item.detail}</p></div><time>{item.time}</time></div>)}</div></article>
          </div>
        </section>

        <section className="simulator-section section-pad" id="simulator">
          <div className="container simulator-grid">
            <div className="simulator-copy"><div className="eyebrow"><span className="eyebrow-line" />{t.simulatorEyebrow}</div><h2>{t.simulatorTitle}</h2><p>{t.simulatorBody}</p><div className="safe-note"><LockKeyhole size={16} /><span><strong>{t.synthetic}</strong><br />{t.noConnection}</span></div><button className="btn btn-reset" onClick={resetSimulation}><RotateCcw size={15} />{t.reset}</button></div>
            <div className="scenario-stack">{scenarios.map(({ id, icon: Icon, key, severity }) => { const isActive = activeScenario === id; const title = key === "command" ? t.scenarioCommand : key === "pattern" ? t.scenarioPattern : t.scenarioLogin; const desc = key === "command" ? t.scenarioCommandDesc : key === "pattern" ? t.scenarioPatternDesc : t.scenarioLoginDesc; return <article className={`scenario-card ${isActive ? "active" : ""} ${severity}`} key={id}><div className="scenario-icon"><Icon size={19} /></div><div className="scenario-content"><div className="scenario-title-row"><h3>{title}</h3><span>{id === "command" ? "CRITICAL" : "ANOMALY"}</span></div><p>{desc}</p>{isActive && <div className="response-note"><span className="response-label"><Check size={13} />{t.response}</span><strong>{t.detected} · {t.contained}</strong><p>{isArabic ? scenarioText[id].responseAr : scenarioText[id].response}</p></div>}</div><button className="btn scenario-btn" onClick={() => runScenario(id)}>{isActive ? <Check size={15} /> : <PlayIcon />}{isActive ? t.detected : t.run}</button></article>; })}</div>
          </div>
        </section>

        <section className="why-section section-pad" id="why-space">
          <div className="container"><div className="section-heading-row why-heading"><div><div className="eyebrow"><span className="eyebrow-line" />{t.why}</div><h2>{t.why}</h2></div><p>{t.whyBody}</p></div><div className="info-grid"><InfoCard number="01" title={t.problem} body={t.problemBody} icon={<ShieldAlert size={19} />} /><InfoCard number="02" title={t.solution} body={t.solutionBody} icon={<Sparkles size={19} />} /><InfoCard number="03" title={t.method} body={t.methodBody} icon={<Cpu size={19} />} /><InfoCard number="04" title={t.impact} body={t.impactBody} icon={<Globe2 size={19} />} /></div></div>
        </section>

        <section className="brief-section section-pad" id="brief">
          <div className="container"><div className="brief-header"><div><div className="eyebrow"><span className="eyebrow-line" />{t.briefEyebrow}</div><h2>{t.briefTitle}</h2></div><span className="brief-stamp"><Check size={15} /> {t.ready}</span></div><div className="brief-grid"><article className="panel brief-main"><div className="paper-kicker">01 / {t.abstract}</div><h3>{copy.en["titleA"]} {copy.en["titleB"]}</h3><p>{t.abstractBody}</p><div className="objectives-block"><div className="paper-kicker">02 / {t.objectives}</div><ul>{t.objectiveItems.map((item) => <li key={item}><span><Check size={13} /></span>{item}</li>)}</ul></div></article><article className="panel presentation-card"><div className="paper-kicker">03 / {t.prototypeDemo}</div><div className="demo-orbit"><div className="demo-earth" /><div className="demo-satellite"><Satellite size={22} /></div></div><h3>{t.prototypeDemo}</h3><p>{t.demoBody}</p><button className="btn btn-outline" onClick={() => scrollToId("simulator")}>{t.simulatorTitle}<ArrowDownRight size={15} /></button></article><article className="panel details-card"><div className="paper-kicker">04 / {t.studentDetails}</div><DetailRow label={t.fullName} value={t.placeholderName} /><DetailRow label={t.college} value={t.placeholderCollege} /><DetailRow label={t.academic} value={t.placeholderAcademic} /><div className="edit-note"><Terminal size={14} /> Edit the bracketed fields in <code>App.tsx</code> before submission.</div></article></div></div>
        </section>

        <section className="disclaimer-section"><div className="container"><div className="disclaimer"><div className="disclaimer-icon"><LockKeyhole size={20} /></div><div><h3>{t.disclaimer}</h3><p>{t.disclaimerBody}</p></div><span className="disclaimer-code">BOUNDARY / 001</span></div></div></section>
      </main>

      <footer className="site-footer"><div className="container footer-inner"><Logo /><span>{t.footer}</span><button onClick={() => scrollToId("top")} className="back-top">Back to top <ArrowUpRight size={14} /></button></div></footer>
    </div>
  );
}

function PlayIcon() { return <span className="play-icon" aria-hidden="true">▶</span>; }

function InfoCard({ number, title, body, icon }: { number: string; title: string; body: string; icon: React.ReactNode }) {
  return <article className="info-card"><div className="info-top"><span className="info-number">{number}</span><span className="info-icon">{icon}</span></div><h3>{title}</h3><p>{body}</p></article>;
}

function DetailRow({ label, value }: { label: string; value: string }) {
  return <div className="detail-row"><span>{label}</span><strong>{value}</strong></div>;
}

export default App;
